# Generated by Django 4.0.3 on 2022-03-06 10:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('u_phn', models.IntegerField(null=True)),
                ('u_address', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='movie_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='movie_rating_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='movie_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.PositiveIntegerField(default=1)),
                ('order_status', models.CharField(choices=[('0', 'Cancelled Order'), ('1', 'Placed Order'), ('2', 'Shipped Order'), ('3', 'Delieverd Order')], default='1', max_length=20)),
                ('order_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='myapp1.client')),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=200)),
                ('m_genre', models.CharField(max_length=200)),
                ('m_relasedate', models.PositiveIntegerField(default=100)),
                ('m_dubbed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2)),
                ('m_writer', models.CharField(max_length=200)),
                ('m_trailer', models.PositiveIntegerField(default=100)),
                ('m_img', models.ImageField(blank=True, null=True, upload_to='m_img/')),
                ('m_on', models.BooleanField(default=True)),
                ('m_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m_o_lan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='myapp1.movie_language')),
                ('m_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='myapp1.movie_type')),
            ],
        ),
        migrations.CreateModel(
            name='m_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='myapp1.client')),
                ('m_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='myapp1.movie_rating_type')),
                ('movie_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_name', to='myapp1.movie')),
            ],
        ),
    ]
