# Generated by Django 4.0.3 on 2022-03-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_rename_u_phn_client_u_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='m_genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_relasedate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_trailer',
            field=models.CharField(max_length=200),
        ),
    ]
