# Generated by Django 4.0.3 on 2022-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_movie_m_relasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='m_relasedate',
            field=models.TimeField(),
        ),
    ]
