# Generated by Django 4.0.3 on 2022-03-31 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp1', '0006_alter_movie_m_relasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='u_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='u_contact',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='c_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='m_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.movie'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_img',
            field=models.ImageField(blank=True, null=True, upload_to='mimages'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_quantity', models.PositiveIntegerField(default=1)),
                ('o_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
