# Generated by Django 4.0.3 on 2022-03-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_client_city_client_locality_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_ge',
            field=models.CharField(choices=[('B', 'Bollywood'), ('H', 'Hollywood')], default='H', max_length=2),
        ),
    ]
