# Generated by Django 4.0.3 on 2022-04-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_movie_movie_ge'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mo_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
