# Generated by Django 4.0.3 on 2022-04-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0010_movie_mo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='locality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='u_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
