# Generated by Django 4.0.3 on 2022-04-02 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp1', '0011_alter_client_city_alter_client_locality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200, null=True)),
                ('c_locality', models.CharField(max_length=200, null=True)),
                ('c_city', models.CharField(max_length=50, null=True)),
                ('c_zipcode', models.CharField(max_length=50, null=True)),
                ('c_contact', models.IntegerField(null=True)),
                ('cus_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
