# Generated by Django 4.0.3 on 2022-04-03 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_item',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='movie_order',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.customer'),
        ),
    ]
