# Generated by Django 4.0.3 on 2022-04-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0014_movie_m_desc_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='m_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
