# Generated by Django 4.0.3 on 2022-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0015_alter_movie_m_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('Cancelled Order', 'Cancelled Order'), ('Placed Order', 'Placed Order'), ('Sent Mail', 'Sent Mail'), ('Activated Link', 'Activated Link')], default='1', max_length=20),
        ),
    ]
